### ISSUE TITLE
MultiFileReader function Read(buf []byte) commit a wrong path with windows

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs-files#16] opened 2019-03-28 08:24 UTC
https://github.com/ipfs/go-ipfs-files/blob/c68472a9b1ec45177ccf8fda607698c86ae0060f/multifilereader.go#L90

this line will make a file with directory like `D:\video\H/p2526321708.webp`
in windows this path is not correct.
i'm used rest to get the file information.
it's result the same directory.
but if i fix to `D:\video\H\p2526321708.webp`
command `ipfs ls /ipfs/#pathcode#` can't display the sub file with this directory.

**Comment by Stebalien** [comment] 2019-03-29 11:44
Where are you observing this behavior? The code you're linking to should _always_ be using unix paths (`a/b/c`) so I'm not sure where the `D:\video\H` part is coming from.

**Comment by godcong** [comment] 2019-03-30 05:50
in windows,in go.
i written an api like `go-ipfs-api`
to get the filename in my project,
api was used this function to add dir.

if i used `multifilereader` to add files,
the post data name was `D:\video\H/p2526321708.webp`.

https://github.com/godcong/go-ipfs-restapi/blob/0529bee4f0363d68a96c296862436bc3bc477b29/add.go#L142

and now, i only can split the all path to get the name use (filepath.Split) from `http://127.0.0.1:5001/api/v0/add` result .

**Comment by Stebalien** [comment] 2019-04-17 18:19
@godcong could you give us the precise steps to reproduce this? It looks like we're failing to convert some paths here.

@djdv could you work with @godcong on this?

**Comment by godcong** [comment] 2019-04-18 16:27
i used the `AddDir` api with `https://github.com/ipfs/go-ipfs-api` and changed the output  to this array:
```
// Object ...
type Object struct {
	Hash string
	Name string
	Size uint64
}
```
now i forked `https://github.com/ipfs/go-ipfs-api` and changes some.

this is the result decode area:
https://github.com/godcong/go-ipfs-restapi/blob/master/add.go#L172

i must split to get filename in json unmashal:
see https://github.com/godcong/go-ipfs-restapi/blob/master/add.go#L23
if not do this it will result a path like `D:\video\H/p2526321708.webp` for me.

**Comment by djdv** [comment] 2019-04-18 16:34
@godcong 
I'm interested in where the source string is originating and what code-path it's taking.
For `go-ipfs` the translation happens around here:
https://github.com/ipfs/go-ipfs-cmds/blob/2e550a162686e63bdccc537fc4726e3239f2d598/cli/parse.go#L292
where we translate command line arguments into api compatible paths.

As well as in the files api in a few places to iterate over the next file in a list
https://github.com/ipfs/go-ipfs-files/blob/c68472a9b1ec45177ccf8fda607698c86ae0060f/serialfile.go#L88

It may be that we need to do something simillar here:
https://github.com/ipfs/go-ipfs-api/blob/96503ab85cc47f2b0e7c8e1bb3346d6937dd55a0/add.go#L93

**Comment by Stebalien** [comment] 2019-04-18 18:32
@godcong could you give us a small program that reproduces this on your machine?

**Comment by godcong** [comment] 2019-04-19 06:02
@djdv 
i renamed old project to
https://github.com/godcong/go-ipfs-restapi-bak/blob/master/add.go#L142

because i think most of the actions are the same as `go-ipfs-api`.

@Stebalien
yes,i add a branch `issues16` and a `main.go` in
https://github.com/godcong/go-ipfs-restapi/tree/issues16/issues/issues16

you can change to any path for add files with `AddDir`:
https://github.com/godcong/go-ipfs-restapi/blob/0a31b2aaec0364b8690123512ed6beccb0826012/issues/issues16/main.go#L10
```
objects, e := s.AddDir("D:\\workspace\\goproject\\go-ipfs-restapi\\issues\\issues16\\")
```

when i use `go run main.go` the output result is:
```	
&{Hash:QmatoEW5Xu8ndYKDeW9h3DcA1oeU7iUHWS6sZ1hYwztf4K Name:D:\workspace\goproject\go-ipfs-restapi\issues\issues16\/main.go Size:321}&{Hash:QmW8hBLAUpvfhFad9L8faSqz6MVyEcz9WTDiDyANLCgQnG Name:D:\workspace\goproject\go-ipfs-restapi\issues\issues16\/test.jpg Size:57804}&{Hash:QmVUo6UeEWpcQCroqRY1uw47eAmZKEFdPJA
r8dh1kpJpx9 Name:D:\workspace\goproject\go-ipfs-restapi\issues\issues16\ Size:58231}
```

in this branch, i only changed 
https://github.com/godcong/go-ipfs-restapi/blob/0a31b2aaec0364b8690123512ed6beccb0826012/add.go#L36
for test.

**Comment by Stebalien** [comment] 2019-04-19 19:48
Ah. Got it. Could you test against #178?

**Comment by godcong** [comment] 2019-04-20 11:50
I have tried to change this:
change `path` to `filepath`.
```
ipfs ls $hash
```
this will result nothing on version 0.4.19/0.4.18, if you add files with `\`.
i'm not sure if it was changed now.

**Comment by Stebalien** [comment] 2019-04-20 20:22
I'm having trouble understanding your comment.

Unfortunately, this change will only affect newly added files. Files added before this change will have `\` in their file-names and, unfortunately, the only solution is to re-add those files.

**Comment by godcong** [comment] 2019-04-22 05:24
i changed the same location and tested.
it's okay.

**Comment by Stebalien** [comment] 2019-04-23 02:20
Thanks!

**Comment by Stebalien** [comment] 2019-04-23 02:21
(fix not yet merged)

**Closed** 2019-04-23 16:08 UTC
Labels: bug
